version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./logs:/var/log/nginx"
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - frontend
    depends_on:
      - grapefruit-web
  mongodb:
    image: mongo
    volumes:
      - "./db:/data/db"
    restart: unless-stopped
    networks:
      - backend
  grapefruit-web:
    image: bashkirtsevich/grapefruit-web
    expose:
      - "8080"
    environment:
      - "VIRTUAL_HOST=grapefruit.localhost.nip.io"
      - "VIRTUAL_PORT=8080"
      - "MONGODB_URL=mongodb://mongodb:27017/grapefruit"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - frontend
      - backend
  grapefruit-crawler:
    image: bashkirtsevich/grapefruit-crawler
    environment:
      - "MONGODB_URL=mongodb://mongodb:27017/grapefruit"
    ports:
      - "6881:6881/udp"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
